name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent on every pull request
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Gemini API configuration
          config.model: "gemini/gemini-3-flash-preview"
          config.fallback_models: '["gemini/gemini-3-pro-preview"]'
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          config.custom_model_max_tokens: 1048576
          # Enable automatic tools
          github_action_config.auto_review: true
          github_action_config.auto_describe: true
          github_action_config.auto_improve: true
          # /improve
          pr_code_suggestions.num_code_suggestions: 6
          # /review
          pr_reviewer.extra_instructions: ${{ secrets.PR_REVIEWER_EXTRA_INSTRUCTIONS }}
          pr_reviewer.require_score_review: true
          pr_reviewer.require_estimate_contribution_time_cost: true
          pr_reviewer.num_max_findings: 10

          # /describe
          pr_description.publish_labels: true
          pr_description.generate_ai_title: true
